pip3 install --upgrade pep8
pip3 install --upgrade cffi
pip3 install --upgrade jedi
pip3 install --upgrade nltk
pip3 install --upgrade rope
pip3 install --upgrade yapf
pip3 install --upgrade black
pip3 install --upgrade pyqt5
pip3 install --upgrade numpy
pip3 install --upgrade scipy
pip3 install --upgrade sympy
pip3 install --upgrade flake8
pip3 install --upgrade pandas
pip3 install --upgrade pygame
pip3 install --upgrade pylint
pip3 install --upgrade sphinx
pip3 install --upgrade ipython
pip3 install --upgrade jupyter
pip3 install --upgrade autopep8
pip3 install --upgrade networkx
pip3 install --upgrade pyflakes
pip3 install --upgrade psycopg2
pip3 install --upgrade pyopengl
pip3 install --upgrade requests
pip3 install --upgrade cx_Freeze
pip3 install --upgrade matplotlib
pip3 install --upgrade sqlalchemy
pip3 install --upgrade virtualenv
pip3 install --upgrade pep8-naming
pip3 install --upgrade pyinstaller
pip3 install --upgrade scikit-image
pip3 install --upgrade scikit-learn
